name: project
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.13.6
  provider: ^6.1.1
  image_picker: ^0.8.4
  firebase_storage: ^11.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  intl: ^0.18.0
  
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Open Sans
      fonts: 
        - asset: assets/fonts/OpenSansRomanRegular.ttf
          weight: 400
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600
